title: Archives
email: me@eliduke.com
description: Archives of the Social Media of Eli Duke
url: "https://archives.eliduke.com"
insta_eli_assets: "https://assets.eliduke.com/archives/instagram/eliduke/"

collections:
  manuals:
    output: true
    permalink: /manuals/:path
  grams:
    output: true
    permalink: /instagram/eliduke/:path
